Postgres test
go-park-mail-ru/2024_1_Netrunners pull request #15
Opened 2024-03-28 11:45 UTC by dozerdozerdozer

tests

2024-04-05 13:46 UTC, labzunova requested changes

2024-04-05 13:46 UTC, labzunova commented on docs/api.yaml
> +<<<<<<< HEAD
красота

2024-04-05 13:46 UTC, labzunova commented on cmd/app/main.go
> -	router.HandleFunc("/profile/{uuid}/preview", usersPageHandlers.GetProfilePreview).Methods("GET", "OPTIONS")
В пр-е отображается что ты это удалил, хотела спросить зачем, а по факту оно на месте
Я не понимаю чет мб...

2024-04-05 13:46 UTC, labzunova commented on internal/domain/actor.go
> +func NewMockActor() ActorData {
Вот эти штуки тебе не в domain бы а рядом с тестами, так как оно только там и нужно, тут в основной логике оно лишнее. В файле с тестами/ возле файла с тестами даже файл/пакет testdata

2024-04-05 13:46 UTC, labzunova commented on internal/middleware/middleware.go
> +		w.Header().Set("Access-Control-Allow-Origin", "http://127.0.0.1:8080")
Если ты сделал это для локального тестинга, то верни
По-хорошему это флагом передавать, чтобы не было такого и все свой флаг подставляли

2024-04-05 13:46 UTC, labzunova commented on internal/repository/postgres/actors.go
> +	"github.com/jackc/pgx/v5/pgconn"
сорт

2024-04-05 13:46 UTC, labzunova commented on internal/repository/postgres/films.go
> +		// &film.AverageScore,
А что это

2024-04-05 13:46 UTC, labzunova commented on internal/service/filmsservice.go
> +					//Data: fmt.Sprintf("Карьера: %s \nРост: %s \nДата рождения: %s \nМесто рождения: %s \n"+
а тут куча комментов это что

2024-04-05 14:11 UTC, dozerdozerdozer commented on docs/api.yaml
> +<<<<<<< HEAD
ужас
исправил

2024-04-05 14:11 UTC, dozerdozerdozer commented on cmd/app/main.go
> -	router.HandleFunc("/profile/{uuid}/preview", usersPageHandlers.GetProfilePreview).Methods("GET", "OPTIONS")
ну оно должно быть, и оно есть )))

2024-04-08 12:49 UTC, labzunova approved these changes

2024-04-08 12:49 UTC, merged