Handlers tests
go-park-mail-ru/2024_1_Netrunners pull request #24
Opened 2024-04-10 12:02 UTC by dozerdozerdozer

handlers tests

2024-04-10 12:21 UTC, labzunova requested changes

2024-04-10 12:21 UTC, labzunova commented on internal/middleware/middleware.go
> +		w.Header().Set("Access-Control-Allow-Origin", "http://127.0.0.1:8080")
прибью
после рк сделаю задачку перенести ip в ручку)))

2024-04-10 12:21 UTC, labzunova commented on internal/service/filmsservice_test.go
> +	"testing"
наверх

2024-04-10 12:38 UTC, dozerdozerdozer commented on internal/middleware/middleware.go
> +		w.Header().Set("Access-Control-Allow-Origin", "http://127.0.0.1:8080")
ахахахахахахах

2024-04-10 12:38 UTC, dozerdozerdozer commented on internal/service/filmsservice_test.go
> +	"testing"
(

2024-04-13 21:50 UTC, labzunova requested changes

2024-04-13 21:50 UTC, labzunova commented on cmd/app/main.go
> +	// err = filmsService.AddSomeData()
Ты либо удали это полностью, либо оставь,  либо сделай заполнение по какому-то флагу дополнительному типа `-fill-db`

2024-04-16 07:04 UTC, labzunova commented on cmd/app/main.go
>  	if err != nil {
![Снимок экрана 2024-04-16 в 10 04 01](https://github.com/go-park-mail-ru/2024_1_Netrunners/assets/61713797/6348ac9b-5bfd-455f-a42e-c685e701190a)
так а ты ошибку от заполнялки убери тож

2024-04-16 09:20 UTC, dozerdozerdozer commented on cmd/app/main.go
>  	if err != nil {
завтыкал( исправил

2024-04-16 09:51 UTC, labzunova approved these changes

2024-04-16 10:52 UTC, merged